name: Paroquia_santo_antonio
description: "Paroquia Santo Antonio"
publish_to: 'none'
version: 2.0.7+38



environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  html: ^0.15.0
  path_provider: ^2.0.5
  path_provider_foundation: ^2.4.0
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  image_picker_ios: ^0.8.12
  mailer: ^6.1.1
  file_picker: ^8.0.6
  file_icon: ^1.0.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.0.2
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.10
  flutter_local_notifications: ^14.0.0
  add_2_calendar: ^2.1.0
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/santo_dia/jpg/
    - assets/
    - assets/biblia/Testamentos/
    - assets/santo_dia/txt/
    - assets/mapas/
    - assets/oracao/
    - assets/imagens/
    - assets/config/.env
    - assets/versao/