name: Paroquia_santo_antonio
description: "Paroquia Santo Antonio"
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  html: ^0.15.0
  path_provider: ^2.0.5
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  intl: ^0.19.0
  url_launcher: ^6.0.12
  image_picker: ^0.8.4+4
  mailer: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/santo_dia/jpg/
    - assets/
    - assets/biblia/Testamentos/
    - assets/santo_dia/txt/
    - assets/mapas/
    - assets/oracao/
    - assets/imagens/