// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-ZjS50Cxqn9EazG-dizYLaxhC8iqEK4',
    appId: '1:725786636481:web:e2dc15c6de662a3bad6440',
    messagingSenderId: '725786636481',
    projectId: 'paroquaia-santo-antonio-limao',
    authDomain: 'paroquaia-santo-antonio-limao.firebaseapp.com',
    databaseURL: 'https://paroquaia-santo-antonio-limao-default-rtdb.firebaseio.com',
    storageBucket: 'paroquaia-santo-antonio-limao.appspot.com',
    measurementId: 'G-ZRVSH73Z5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdN-fUf3jggQxPfVDMPRP912JRIdITruE',
    appId: '1:725786636481:android:529305467b355611ad6440',
    messagingSenderId: '725786636481',
    projectId: 'paroquaia-santo-antonio-limao',
    databaseURL: 'https://paroquaia-santo-antonio-limao-default-rtdb.firebaseio.com',
    storageBucket: 'paroquaia-santo-antonio-limao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOoUEg_xlQBbU2sFTV7BM6GCH7JYFSVU',
    appId: '1:725786636481:ios:d78b3dbf67cce30fad6440',
    messagingSenderId: '725786636481',
    projectId: 'paroquaia-santo-antonio-limao',
    databaseURL: 'https://paroquaia-santo-antonio-limao-default-rtdb.firebaseio.com',
    storageBucket: 'paroquaia-santo-antonio-limao.appspot.com',
    iosBundleId: 'com.example.paroquiaSantoAntonioLimao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEOoUEg_xlQBbU2sFTV7BM6GCH7JYFSVU',
    appId: '1:725786636481:ios:cbe6a06fb385b386ad6440',
    messagingSenderId: '725786636481',
    projectId: 'paroquaia-santo-antonio-limao',
    databaseURL: 'https://paroquaia-santo-antonio-limao-default-rtdb.firebaseio.com',
    storageBucket: 'paroquaia-santo-antonio-limao.appspot.com',
    iosBundleId: 'com.example.paroquiaSantoAntonioLimao.RunnerTests',
  );
}
