// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTnSPbqFtYg_dmlhXWoYNmgz6PyPnJhJI',
    appId: '1:831299082694:web:680f4f6f58b73c2d17fac7',
    messagingSenderId: '831299082694',
    projectId: 'psantoantoniolimao',
    authDomain: 'psantoantoniolimao.firebaseapp.com',
    databaseURL: 'https://psantoantoniolimao-default-rtdb.firebaseio.com',
    storageBucket: 'psantoantoniolimao.appspot.com',
    measurementId: 'G-CXYW4TVSQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSxUT3KvZuXqTFppNcHi1-tYa_87_Z4g',
    appId: '1:831299082694:android:e3b161ff58b1121517fac7',
    messagingSenderId: '831299082694',
    projectId: 'psantoantoniolimao',
    databaseURL: 'https://psantoantoniolimao-default-rtdb.firebaseio.com',
    storageBucket: 'psantoantoniolimao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUXQwEUd4slh_DPVPJOodmj9lafGhNuMs',
    appId: '1:831299082694:ios:2ea8c38770bd47ca17fac7',
    messagingSenderId: '831299082694',
    projectId: 'psantoantoniolimao',
    databaseURL: 'https://psantoantoniolimao-default-rtdb.firebaseio.com',
    storageBucket: 'psantoantoniolimao.appspot.com',
    iosBundleId: 'com.paroquia.paroquiaSantoAntonioLimao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUXQwEUd4slh_DPVPJOodmj9lafGhNuMs',
    appId: '1:831299082694:ios:f60370310cb5481f17fac7',
    messagingSenderId: '831299082694',
    projectId: 'psantoantoniolimao',
    databaseURL: 'https://psantoantoniolimao-default-rtdb.firebaseio.com',
    storageBucket: 'psantoantoniolimao.appspot.com',
    iosBundleId: 'com.paroquia.paroquiaSantoAntonioLimao.RunnerTests',
  );
}
